[project]
name = "cchardet"
authors = [{ name = "PyYoshi", email = "myoshi321go@gmail.com" }]
urls.Homepage = 'https://github.com/PyYoshi/cChardet'
description = 'cChardet is high speed universal character encoding detector.'
readme = { file = 'README.md', content-type = 'text/markdown' }
license = { file = "COPYING" }
classifiers = [
    'License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)',
    'License :: OSI Approved :: GNU General Public License (GPL)',
    'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
    'Programming Language :: Cython',
    'Programming Language :: Python',
    'Topic :: Software Development :: Libraries',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]
requires-python = ">= 3.9"
dynamic = ["version"]

[build-system]
requires = ["setuptools", "wheel", "cython", "pkgconfig", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project.scripts]
cchardetect = "cchardet.cli.cchardetect:main"

[tool.setuptools_scm]
# enables setuptools_scm to provide the dynamic version


[tool.rye]
dev-dependencies = [
    "chardet>=5.2.0",
    "cython>=3.0.10",
    "setuptools>=70.0.0",
    "pytest>=8.2.1",
    "ruff>=0.4.6",
]

[tool.ruff]
exclude = ["src/ext"]
line-length = 100
target-version = "py39"
lint.select = ["E", "F", "I", "N"]
format.quote-style = "double"
format.indent-style = "space"

[tool.cibuildwheel]
build-frontend = "build"
skip = ["*-win32"]
archs = ["auto"]
test-requires = ['pytest']
test-command = [
    'cd {project}',
    'python -m pytest {project}'
]

environment = {INCLUDE_PATH="/usr/local/include/uchardet", LIBRARY_PATH="/usr/local/lib64/"}
before-build = [
    "git submodule sync --recursive",
    "git submodule update --init --force --recursive --depth=1",
]

[tool.cibuildwheel.macos]
environment = {INCLUDE_PATH="/usr/local/include/uchardet", LIBRARY_PATH="/usr/local/lib/"}
before-build = [
    "git submodule sync --recursive",
    "git submodule update --init --force --recursive --depth=1",
]

[tool.cibuildwheel.windows]
before-build = [
    "git submodule sync --recursive",
    "git submodule update --init --force --recursive --depth=1",
    "make pip"
]
