[build-system]
requires = ["setuptools", "wheel", "cython", "pkgconfig"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "build"
build = "cp3*"
skip = ["*-win32", "*-manylinux_i686", "*-musllinux_*"]
archs = ["auto64"]
test-requires = ['pytest']
test-command = ['python -m pytest']

[tool.cibuildwheel.windows]
before-build = [
    "make pip"
]
